// Auto-generated by Phase B (P0 link pass). Defines all primitive-typed
// `extern "C"` globals that are declared-but-not-defined across the src/
// tree, so the normal-build linker can resolve them. The values are
// zero-initialised; in the orig exe these slots are populated by their
// owning modules (Supervisor, GameManager, etc.) during startup, and as
// those modules reverse these definitions will move into them. This file
// is part of the normal build only and does NOT contribute to objdiff.
//
// For const f32 rdata constants the zero value is a placeholder; the real
// numeric values live in orig .rdata and are recovered on the objdiff
// side via scripts/generate_objdiff_objs.py SYMBOL_MAP.

#include "inttypes.hpp"

// AnmManager::SetRenderStateForVm colour-slot dwords (software render path
// stamps these when GCOS_DONT_USE_VERTEX_BUF is set). Orig addresses
// 0x4b9fb8..0x4ba0cc. Zero-init here; populated by SetRenderStateForVm.
extern "C" u32 g_AnmMgrColorSlot_4b9fb8 = 0;
extern "C" u32 g_AnmMgrColorSlot_4b9fd4 = 0;
extern "C" u32 g_AnmMgrColorSlot_4b9ff0 = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba00c = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba084 = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba09c = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba0b4 = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba0cc = 0;
// Ignored `this` passed to Supervisor_Setup3DCamera / _2DCamera (orig 0x1347b00).
extern "C" u8 g_SupervisorCameraStub_1347b00 = 0;
// cfg.opts bitfield mirror (orig 0x575a9c = g_Supervisor.cfg.opts). Read as
// an absolute address by SetRenderStateForVm to match orig's addressing.
extern "C" u32 g_SupervisorCfgOpts_575a9c = 0;
// D3D device pointer slot (orig 0x575958). Set by Supervisor at boot.
extern "C" void *g_SupervisorD3dDevice_575958 = 0;
// DrawPrimitiveUP vertex buffer for the software (no-vertex-buffer) path
// (orig 0x4ba078). 4 * VertexTex1Xyzrwh = 0x60 bytes; initialised at startup.
extern "C" u8 g_DrawPrimUpVerts_4ba078[0x60] = {0};
// Per-texture-format bytes-per-pixel table (orig 0x495144). Indexed by the
// same format index as g_TextureFormatD3D8Mapping (UNKNOWN/A8R8G8B8/A1R5G5B5/
// R5G6B5/R8G8B8/A4R4G4B4). Values lifted from the orig .rdata dump.
extern "C" u32 g_TextureFormatBytesPerPixel_495144[6] = {
    4, // UNKNOWN  (treated as 32-bit)
    4, // A8R8G8B8 (32-bit)
    2, // A1R5G5B5 (16-bit)
    2, // R5G6B5   (16-bit)
    3, // R8G8B8   (24-bit)
    2, // A4R4G4B4 (16-bit)
};

extern "C" const f32 g_AsciiC0x498a50 = 0.0f;
extern "C" const f32 g_AsciiC0x498a80 = 0.0f;
extern "C" u8 g_AsciiIsInGameMenu = 0;
extern "C" u8 g_AsciiIsInRetryMenu = 0;
extern "C" f32 g_AsciiPopupOffsetX = 0.0f;
extern "C" f32 g_AsciiPopupOffsetY = 0.0f;
extern "C" const f32 g_BombC0x498768 = 0.0f;
extern "C" const f32 g_BombC0x498a64 = 0.0f;
extern "C" const f32 g_BombC0x498a70 = 0.0f;
extern "C" const f32 g_BombC0x498a8c = 0.0f;
extern "C" const f32 g_BombC0x498b08 = 0.0f;
extern "C" const f32 g_BombC0x498b2c = 0.0f;
extern "C" const f32 g_BombC0x498b54 = 0.0f;
extern "C" const f32 g_BombC0x498c68 = 0.0f;
extern "C" const f32 g_BombC0x498c74 = 0.0f;
extern "C" const f32 g_BombC0x498c7c = 0.0f;
extern "C" const f32 g_BombC0x498c80 = 0.0f;
extern "C" const f32 g_BombC0x498ce4 = 0.0f;
extern "C" const f32 g_BombC0x498ce8 = 0.0f;
extern "C" f32 g_BombG0x62f864 = 0.0f;
extern "C" f32 g_BombG0x62f868 = 0.0f;
extern "C" i32 g_BombIsActive = 0;
extern "C" u8 g_BombPreDrawFlag = 0;
extern "C" u8 g_BombPreDrawFlag2 = 0;
extern "C" u8 g_BombStartedFlag = 0;
extern "C" u8 g_BombUsedFlags = 0;
extern "C" i32 g_Cherry = 0;
extern "C" i32 g_DyingTimer = 0;
extern "C" u8 g_EffectMgrPlayModeA = 0;
extern "C" i8 g_GameManagerRankForceFlag = 0;
extern "C" u32 g_GameManagerStatusBitfield = 0;
extern "C" i32 g_GameManager_currentStage = 0;
extern "C" const f32 g_GameMgrC0x498a68 = 0.0f;
extern "C" const f32 g_GameMgrC0x498a6c = 0.0f;
extern "C" const f32 g_GameMgrC0x498a80 = 0.0f;
extern "C" const f32 g_GameMgrC0x498a84 = 0.0f;
extern "C" const f32 g_GameMgrC0x498a8c = 0.0f;
extern "C" const f32 g_GameMgrC0x498b24 = 0.0f;
extern "C" const f32 g_GameMgrC0x498bac = 0.0f;
extern "C" const f32 g_GameMgrC0x498c7c = 0.0f;
extern "C" const f32 g_GameMgrC0x498c80 = 0.0f;
extern "C" u32 g_GameMgrG0x1347fe4 = 0;
extern "C" i32 g_GameMgrG0x49fbf0 = 0;
extern "C" u16 g_GameMgrG0x49fe20 = 0;
extern "C" i32 g_GameMgrG0x49fe24 = 0;
extern "C" i32 g_GameMgrG0x62f50c = 0;
extern "C" i32 g_GameMgrG0x62f510 = 0;
extern "C" i32 g_GameMgrG0x62f528 = 0;
extern "C" i32 g_GameMgrG0x62f534 = 0;
extern "C" i32 g_GameMgrG0x62f614 = 0;
extern "C" i32 g_GameMgrG0x62f618 = 0;
extern "C" i32 g_GameMgrG0x62f630 = 0;
extern "C" i32 g_GameMgrG0x62f63c = 0;
extern "C" u8 g_GameMgrG0x62f647 = 0;
extern "C" u8 g_GameMgrG0x62f64f = 0;
extern "C" i32 g_GameMgrG0x62f654 = 0;
extern "C" f32 g_GameMgrG0x62f884 = 0.0f;
extern "C" i32 g_GameMgrG0x9a9a80 = 0;
extern "C" f32 g_GameMgr_arcadeOffsetX = 0.0f;
extern "C" f32 g_GameMgr_arcadeOffsetY = 0.0f;
extern "C" f32 g_GameMgr_arcadeRegionH = 0.0f;
extern "C" f32 g_GameMgr_arcadeRegionW = 0.0f;
extern "C" u8 g_GameMgr_character = 0;
extern "C" u8 g_GameMgr_characterShotType = 0;
extern "C" i32 g_GameMgr_currentScore = 0;
extern "C" u8 g_GameMgr_difficulty = 0;
extern "C" i32 g_GameMgr_isInGame = 0;
extern "C" u8 g_GameMgr_isInRetryMenu = 0;
extern "C" u8 g_GameMgr_shotType = 0;
extern "C" u16 g_GuiCounter1 = 0;
extern "C" u32 g_GuiCounter2 = 0;
extern "C" u8 g_GuiCounterSlots[0x24c * 4] = {0};
extern "C" u32 g_GuiSpriteFlags = 0;
extern "C" int g_LastFileSize = 0;
extern "C" i32 g_ScoreDisplay = 0;
extern "C" i32 g_ScoreFrame = 0;
extern "C" i8 g_ScreenEffectG0x62627c = 0;
extern "C" const f32 g_SupervisorC0x498a48 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a4c = 0.0f;
extern "C" const f32 g_SupervisorC0x498a50 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a54 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a58 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a68 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a6c = 0.0f;
extern "C" const f32 g_SupervisorC0x498aa0 = 0.0f;
extern "C" const f32 g_SupervisorC0x498ab8 = 0.0f;
extern "C" const f32 g_SupervisorC0x498b10 = 0.0f;
extern "C" const f32 g_SupervisorC0x498b14 = 0.0f;
extern "C" const f32 g_SupervisorC0x498b18 = 0.0f;
extern "C" const f32 g_SupervisorC0x498b1c = 0.0f;
extern "C" const f32 g_SupervisorC0x498b20 = 0.0f;
extern "C" i32 g_SupervisorG0x13542d8 = 0;
extern "C" i32 g_SupervisorG0x135dfec = 0;
extern "C" char g_SupervisorG0x135dff0[0x80] = {0};
extern "C" char g_SupervisorG0x135e0f0[0x80] = {0};
extern "C" i32 g_SupervisorG0x135e1f0 = 0;
// App mutex handle (orig DAT_0135e1f4). Created by CheckAlreadyRunning
// (FUN_00435bd0) via CreateMutexA("Touhou YouYouMu App").
extern "C" void *g_SupervisorAppMutex_135e1f4 = 0;
extern "C" i32 g_SupervisorG0x135e298 = 0;
extern "C" i32 g_SupervisorG0x135e29c = 0;
extern "C" i32 g_SupervisorG0x135e2a0 = 0;
extern "C" i32 g_SupervisorG0x135e2a4 = 0;
extern "C" u16 g_SupervisorG0x49fe20 = 0;
extern "C" u32 g_SupervisorG0x4b9e64 = 0;
extern "C" i32 g_SupervisorG0x4bdaa0 = 0;
extern "C" i32 g_SupervisorViewport_575a18 = 0;
extern "C" i32 g_SupervisorG0x575a1c = 0;
extern "C" i32 g_SupervisorG0x575a20 = 0;
extern "C" i32 g_SupervisorG0x575a24 = 0;
extern "C" f32 g_SupervisorG0x575a28 = 0.0f;
extern "C" f32 g_SupervisorG0x575a2c = 0.0f;
extern "C" i32 g_SupervisorG0x575bbc = 0;
extern "C" i32 g_SupervisorG0x575bf8 = 0;
extern "C" i32 g_SupervisorG0x575c08 = 0;
extern "C" u8 g_SupervisorG0x575c0c = 0;
extern "C" i32 g_SupervisorG0x575c10 = 0;
extern "C" i32 g_SupervisorG0x575c14 = 0;
extern "C" u32 g_SupervisorG0x62f4e0 = 0;
extern "C" u16 g_SupervisorG0x62f4e4 = 0;
extern "C" u16 g_SupervisorG0x62f4e6 = 0;
extern "C" u8 g_SupervisorG0x62f4e8 = 0;
extern "C" i32 g_SupervisorG0x62f85c = 0;
extern "C" f32 g_Supervisor_framerateMul = 0.0f;

// ============================================================================
// Pointer / struct-typed globals that were filtered out of the auto-generated
// section above (they're declared as void*/char*/struct* across the codebase,
// not primitive scalars). Defined here as zero-initialised slots so the normal
// build links. As their owning modules reverse, these move into them.
// ============================================================================

// AnmManager singleton pointers (multiple modules alias the same DAT_004b9e44).
extern "C" void *g_AsciiAnmMgr = 0;     // AnmMgrStub* @ 0x4b9e44 (AsciiManager.cpp)
extern "C" void *g_BombDataAnmMgr = 0;  // void*        @ 0x4b9e44 (BombData.cpp)
// GameManager pointers (string / state slots).
extern "C" void *g_GameMgrG0x1347938 = 0;
extern "C" char *g_GameMgrG0x497e1c = 0;
extern "C" char *g_GameMgrG0x497e30 = 0;
extern "C" char *g_GameMgrG0x497e58 = 0;
extern "C" char *g_GameMgrG0x497e84 = 0;
extern "C" char *g_GameMgrG0x497f4c = 0;
extern "C" char *g_GameMgrG0x498010 = 0;
extern "C" char *g_GameMgrG0x498038 = 0;
extern "C" char *g_GameMgrG0x498064 = 0;
extern "C" char *g_GameMgrG0x498524 = 0;
extern "C" char *g_GameMgrG0x4986b4 = 0;
extern "C" char *g_GameMgrG0x49f560 = 0;
extern "C" char *g_GameMgrG0x49f588 = 0;
extern "C" char *g_GameMgrG0x49f58c = 0;
extern "C" void *g_GameMgrG0x1347f9c = 0;
// Gui object pointer (Player.cpp / Supervisor.cpp).
extern "C" void *g_GuiObjPtr = 0;
// Pbg4 LZSS static state (Pbg4Parser references).
// Sizes must match orig .bss layout (DAT_0049fe30 = 0x2001 nodes * 0xc bytes).
extern "C" i32 g_Pbg4CurIndex = 0;
extern "C" u8 g_Pbg4Dict[0x2000] = {0};
extern "C" u8 g_Pbg4Nodes[0x2001 * 0xc] = {0};
// ScreenEffect Rng instance (ScreenEffect.cpp).
extern "C" void *g_ScreenEffectRng = 0;
// Supervisor rdata/state pointers (Supervisor.cpp).
extern "C" void *g_SupervisorG0x496c0c = 0;
extern "C" void *g_SupervisorG0x4980c4 = 0;
extern "C" void *g_SupervisorG0x4bd994 = 0;
extern "C" void *g_SupervisorG0x575a64 = 0;
extern "C" void *g_SupervisorG0x575a68 = 0;
// Player-specific AnmManager / ScoreSub / EffectManager / SoundManager handles.
extern "C" void *g_AnmManagerFilesObj_P = 0;  // document-only alias (not currently referenced)

// AnmManager::ExecuteScript rdata float constants (orig .rdata slots).
// These mirror the const-float DAT_ addresses read absolutely by FUN_00450d60.
extern "C" const f32 g_AnmMgrC0x498a4c = 0.0f;   // DAT_00498A4C (sentinel)
extern "C" const f32 g_AnmMgrC0x498a54 = 1.0f;   // DAT_00498A54 (angle modulus)
extern "C" const f32 g_AnmMgrC0x498b5c = -1.0f;  // DAT_00498B5C (scale flip)
// Supervisor.framerateMultiplier mirror (orig 0x575ac8); ExecuteScript reads
// it absolutely. Zero-init matches the boot state until Supervisor sets it.
extern "C" f32 g_AnmMgrFramerateMul_575ac8 = 0.0f;

// P1.3 Supervisor boot-path globals (FUN_00434020/a40/a80/bd0/46e0/3e90).
// These are standalone .data/.bss globals the boot helpers reach via absolute
// address. Zero-init matches orig boot state; InitD3D / CreateWindow populate
// them as the device / window come up.
extern "C" void *g_SupervisorWindow_575c20 = 0;          // HWND
extern "C" i32  g_SupervisorExStyle_575c28 = 0;
extern "C" i32  g_SupervisorStyle_575c2c = 0;
extern "C" i32  g_SupervisorExitFlag_575c24 = 0;
extern "C" i32  g_SupervisorBootVar_575c30 = 0;
extern "C" i64  g_SupervisorPerfFreq_575c34 = 0;          // QueryPerformanceFrequency
extern "C" i32  g_SupervisorSysParam_575c40 = 0;          // SPI screensaver
extern "C" i32  g_SupervisorSysParam_575c44 = 0;          // SPI keyboard delay
extern "C" i32  g_SupervisorSysParam_575c48 = 0;          // SPI keyboard speed
extern "C" u8   g_SupervisorLoadResult_575c3c = 0;
extern "C" u8   g_SupervisorColorMode_575a86 = 0;
extern "C" u8   g_SupervisorIsForeground_575a8a = 0;
extern "C" u8   g_SupervisorFrameskipCfg_575a8b = 0;
extern "C" u8   g_SupervisorUnkFlag_575a8c = 0;
extern "C" u8   g_SupervisorWindowedOverride_575abc = 0;
extern "C" i32  g_SupervisorUnkAb4_575ab4 = 0;
extern "C" i32  g_SupervisorUnkAc0_575ac0 = 0;
extern "C" i32  g_SupervisorHasHwVertexProc_575ac4 = 0;
extern "C" i32  g_SupervisorFrameFlags_575adc = 0;
extern "C" i32  g_SupervisorUnkAe8_575ae8 = 0;
extern "C" u32  g_SupervisorVramMegs_575b40 = 0;
extern "C" u32  g_SupervisorUnkB78_575b78 = 0;
extern "C" char  g_GameErrorContext_624210[0x2008] = {0};
extern "C" void *g_GameErrorContextHead_626210 = 0;
extern "C" i32  g_SupervisorQpcLastLo_135e208 = 0;
extern "C" i32  g_SupervisorQpcLastHi_135e20c = 0;
extern "C" f64  g_SupervisorTimeLast_135e200 = 0;
extern "C" i32  g_SupervisorFrameCounter_135e1f8 = 0;
extern "C" u32  g_SupervisorPresentParams_575a30[13] = {0};
// g_SupervisorViewport_575a18 already defined as i32 earlier (as
// g_SupervisorViewport_575a18); the boot helpers index it as u32[8] via the
// same address. Kept as-is; the union alias is fine since both are 0-init.
extern "C" u32  g_SupervisorUnkMatrix1_575990[16] = {0};
extern "C" u32  g_SupervisorUnkMatrix2_5759d0[16] = {0};
extern "C" void *g_SupervisorHwndMirror_575994 = 0;
extern "C" void *g_SupervisorAnmMgrSlot_4b9e44 = 0;
extern "C" void *g_SupervisorHInstance_575950 = 0;
extern "C" void *g_SupervisorD3D8_575954 = 0;
// g_SupervisorReplayActive_62f4e0 is a separate symbol from the
// wav-format-table g_SupervisorG0x62f4e0 (also at DAT_0062f4e0). Both alias
// the same address; the boot loop reads it as a replay-active flag.
extern "C" i32  g_SupervisorReplayActive_62f4e0 = 0;
// Error message title rdata pointer (orig 0x497c78); reached absolutely by
// the boot loop's MessageBoxA in Teardown. Zero-init placeholder.
extern "C" char *g_SupervisorErrTitle_497c78 = 0;
// Per-frame input/pad flag (orig 0x575c0c); stamped each frame by RunSession.
extern "C" u8 g_SupervisorFrameInputFlag_575c0c = 0;


extern "C" f64  g_PlayerAbsorbSizeZero = 0.0;             // rdata (double 0.0; shared by CalcBulletAbsorption size threshold)
extern "C" f64  g_SupervisorFrametime_498bc0 = 0.0;       // rdata (placeholder)
extern "C" f64  g_SupervisorFrametime2_498bc8 = 0.0;      // rdata (placeholder)

