// Auto-generated by Phase B (P0 link pass). Defines all primitive-typed
// `extern "C"` globals that are declared-but-not-defined across the src/
// tree, so the normal-build linker can resolve them. The values are
// zero-initialised; in the orig exe these slots are populated by their
// owning modules (Supervisor, GameManager, etc.) during startup, and as
// those modules reverse these definitions will move into them. This file
// is part of the normal build only and does NOT contribute to objdiff.
//
// For const f32 rdata constants the zero value is a placeholder; the real
// numeric values live in orig .rdata and are recovered on the objdiff
// side via scripts/generate_objdiff_objs.py SYMBOL_MAP.

#include "inttypes.hpp"

// AnmManager::SetRenderStateForVm colour-slot dwords (software render path
// stamps these when GCOS_DONT_USE_VERTEX_BUF is set). Orig addresses
// 0x4b9fb8..0x4ba0cc. Zero-init here; populated by SetRenderStateForVm.
extern "C" u32 g_AnmMgrColorSlot_4b9fb8 = 0;
extern "C" u32 g_AnmMgrColorSlot_4b9fd4 = 0;
extern "C" u32 g_AnmMgrColorSlot_4b9ff0 = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba00c = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba084 = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba09c = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba0b4 = 0;
extern "C" u32 g_AnmMgrColorSlot_4ba0cc = 0;
// Ignored `this` passed to Supervisor_Setup3DCamera / _2DCamera (orig 0x1347b00).
extern "C" u8 g_SupervisorCameraStub_1347b00 = 0;
// cfg.opts bitfield mirror (orig 0x575a9c = g_Supervisor.cfg.opts). Read as
// an absolute address by SetRenderStateForVm to match orig's addressing.
extern "C" u32 g_SupervisorCfgOpts_575a9c = 0;
// D3D device pointer slot (orig 0x575958). Set by Supervisor at boot.
extern "C" void *g_SupervisorD3dDevice_575958 = 0;
// DrawPrimitiveUP vertex buffer for the software (no-vertex-buffer) path
// (orig 0x4ba078). 4 * VertexTex1Xyzrwh = 0x60 bytes; initialised at startup.
extern "C" u8 g_DrawPrimUpVerts_4ba078[0x60] = {0};
// Per-texture-format bytes-per-pixel table (orig 0x495144). Indexed by the
// same format index as g_TextureFormatD3D8Mapping (UNKNOWN/A8R8G8B8/A1R5G5B5/
// R5G6B5/R8G8B8/A4R4G4B4). Values lifted from the orig .rdata dump.
extern "C" u32 g_TextureFormatBytesPerPixel_495144[6] = {
    4, // UNKNOWN  (treated as 32-bit)
    4, // A8R8G8B8 (32-bit)
    2, // A1R5G5B5 (16-bit)
    2, // R5G6B5   (16-bit)
    3, // R8G8B8   (24-bit)
    2, // A4R4G4B4 (16-bit)
};

extern "C" const f32 g_AsciiC0x498a50 = 0.0f;
extern "C" const f32 g_AsciiC0x498a80 = 0.0f;
extern "C" u8 g_AsciiIsInGameMenu = 0;
extern "C" u8 g_AsciiIsInRetryMenu = 0;
extern "C" f32 g_AsciiPopupOffsetX = 0.0f;
extern "C" f32 g_AsciiPopupOffsetY = 0.0f;
extern "C" const f32 g_BombC0x498768 = 0.0f;
extern "C" const f32 g_BombC0x498a64 = 0.0f;
extern "C" const f32 g_BombC0x498a70 = 0.0f;
extern "C" const f32 g_BombC0x498a8c = 0.0f;
extern "C" const f32 g_BombC0x498b08 = 0.0f;
extern "C" const f32 g_BombC0x498b2c = 0.0f;
extern "C" const f32 g_BombC0x498b54 = 0.0f;
extern "C" const f32 g_BombC0x498c68 = 0.0f;
extern "C" const f32 g_BombC0x498c74 = 0.0f;
extern "C" const f32 g_BombC0x498c7c = 0.0f;
extern "C" const f32 g_BombC0x498c80 = 0.0f;
extern "C" const f32 g_BombC0x498ce4 = 0.0f;
extern "C" const f32 g_BombC0x498ce8 = 0.0f;
extern "C" f32 g_BombG0x62f864 = 0.0f;
extern "C" f32 g_BombG0x62f868 = 0.0f;
extern "C" i32 g_BombIsActive = 0;
extern "C" u8 g_BombPreDrawFlag = 0;
extern "C" u8 g_BombPreDrawFlag2 = 0;
extern "C" u8 g_BombStartedFlag = 0;
extern "C" u8 g_BombUsedFlags = 0;
extern "C" i32 g_Cherry = 0;
extern "C" i32 g_DyingTimer = 0;
extern "C" u8 g_EffectMgrPlayModeA = 0;
extern "C" i8 g_GameManagerRankForceFlag = 0;
extern "C" u32 g_GameManagerStatusBitfield = 0;
extern "C" i32 g_GameManager_currentStage = 0;
extern "C" const f32 g_GameMgrC0x498a68 = 0.0f;
extern "C" const f32 g_GameMgrC0x498a6c = 0.0f;
extern "C" const f32 g_GameMgrC0x498a80 = 0.0f;
extern "C" const f32 g_GameMgrC0x498a84 = 0.0f;
extern "C" const f32 g_GameMgrC0x498a8c = 0.0f;
extern "C" const f32 g_GameMgrC0x498b24 = 0.0f;
extern "C" const f32 g_GameMgrC0x498bac = 0.0f;
extern "C" const f32 g_GameMgrC0x498c7c = 0.0f;
extern "C" const f32 g_GameMgrC0x498c80 = 0.0f;
extern "C" u32 g_GameMgrG0x1347fe4 = 0;
extern "C" i32 g_GameMgrG0x49fbf0 = 0;
extern "C" u16 g_GameMgrG0x49fe20 = 0;
extern "C" i32 g_GameMgrG0x49fe24 = 0;
extern "C" i32 g_GameMgrG0x62f50c = 0;
extern "C" i32 g_GameMgrG0x62f510 = 0;
extern "C" i32 g_GameMgrG0x62f528 = 0;
extern "C" i32 g_GameMgrG0x62f534 = 0;
extern "C" i32 g_GameMgrG0x62f614 = 0;
extern "C" i32 g_GameMgrG0x62f618 = 0;
extern "C" i32 g_GameMgrG0x62f630 = 0;
extern "C" i32 g_GameMgrG0x62f63c = 0;
extern "C" u8 g_GameMgrG0x62f647 = 0;
extern "C" u8 g_GameMgrG0x62f64f = 0;
extern "C" i32 g_GameMgrG0x62f654 = 0;
extern "C" f32 g_GameMgrG0x62f884 = 0.0f;
extern "C" i32 g_GameMgrG0x9a9a80 = 0;
extern "C" f32 g_GameMgr_arcadeOffsetX = 0.0f;
extern "C" f32 g_GameMgr_arcadeOffsetY = 0.0f;
extern "C" f32 g_GameMgr_arcadeRegionH = 0.0f;
extern "C" f32 g_GameMgr_arcadeRegionW = 0.0f;
extern "C" u8 g_GameMgr_character = 0;
extern "C" u8 g_GameMgr_characterShotType = 0;
extern "C" i32 g_GameMgr_currentScore = 0;
extern "C" u8 g_GameMgr_difficulty = 0;
extern "C" i32 g_GameMgr_isInGame = 0;
extern "C" u8 g_GameMgr_isInRetryMenu = 0;
extern "C" u8 g_GameMgr_shotType = 0;
extern "C" u16 g_GuiCounter1 = 0;
extern "C" u32 g_GuiCounter2 = 0;
extern "C" u8 g_GuiCounterSlots[0x24c * 4] = {0};
extern "C" u32 g_GuiSpriteFlags = 0;
extern "C" int g_LastFileSize = 0;
extern "C" i32 g_ScoreDisplay = 0;
extern "C" i32 g_ScoreFrame = 0;
extern "C" i8 g_ScreenEffectG0x62627c = 0;
extern "C" const f32 g_SupervisorC0x498a48 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a4c = 0.0f;
extern "C" const f32 g_SupervisorC0x498a50 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a54 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a58 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a68 = 0.0f;
extern "C" const f32 g_SupervisorC0x498a6c = 0.0f;
extern "C" const f32 g_SupervisorC0x498aa0 = 0.0f;
extern "C" const f32 g_SupervisorC0x498ab8 = 0.0f;
extern "C" const f32 g_SupervisorC0x498b10 = 0.0f;
extern "C" const f32 g_SupervisorC0x498b14 = 0.0f;
extern "C" const f32 g_SupervisorC0x498b18 = 0.0f;
extern "C" const f32 g_SupervisorC0x498b1c = 0.0f;
extern "C" const f32 g_SupervisorC0x498b20 = 0.0f;
extern "C" i32 g_SupervisorG0x13542d8 = 0;
extern "C" i32 g_SupervisorG0x135dfec = 0;
extern "C" char g_SupervisorG0x135dff0[0x80] = {0};
extern "C" char g_SupervisorG0x135e0f0[0x80] = {0};
extern "C" i32 g_SupervisorG0x135e1f0 = 0;
extern "C" i32 g_SupervisorG0x135e298 = 0;
extern "C" i32 g_SupervisorG0x135e29c = 0;
extern "C" i32 g_SupervisorG0x135e2a0 = 0;
extern "C" i32 g_SupervisorG0x135e2a4 = 0;
extern "C" u16 g_SupervisorG0x49fe20 = 0;
extern "C" u32 g_SupervisorG0x4b9e64 = 0;
extern "C" i32 g_SupervisorG0x4bdaa0 = 0;
extern "C" i32 g_SupervisorViewport_575a18 = 0;
extern "C" i32 g_SupervisorG0x575a1c = 0;
extern "C" i32 g_SupervisorG0x575a20 = 0;
extern "C" i32 g_SupervisorG0x575a24 = 0;
extern "C" f32 g_SupervisorG0x575a28 = 0.0f;
extern "C" f32 g_SupervisorG0x575a2c = 0.0f;
extern "C" i32 g_SupervisorG0x575bbc = 0;
extern "C" i32 g_SupervisorG0x575bf8 = 0;
extern "C" i32 g_SupervisorG0x575c08 = 0;
extern "C" u8 g_SupervisorG0x575c0c = 0;
extern "C" i32 g_SupervisorG0x575c10 = 0;
extern "C" i32 g_SupervisorG0x575c14 = 0;
extern "C" u32 g_SupervisorG0x62f4e0 = 0;
extern "C" u16 g_SupervisorG0x62f4e4 = 0;
extern "C" u16 g_SupervisorG0x62f4e6 = 0;
extern "C" u8 g_SupervisorG0x62f4e8 = 0;
extern "C" i32 g_SupervisorG0x62f85c = 0;
extern "C" f32 g_Supervisor_framerateMul = 0.0f;

// ============================================================================
// Pointer / struct-typed globals that were filtered out of the auto-generated
// section above (they're declared as void*/char*/struct* across the codebase,
// not primitive scalars). Defined here as zero-initialised slots so the normal
// build links. As their owning modules reverse, these move into them.
// ============================================================================

// AnmManager singleton pointers (multiple modules alias the same DAT_004b9e44).
extern "C" void *g_AsciiAnmMgr = 0;     // AnmMgrStub* @ 0x4b9e44 (AsciiManager.cpp)
extern "C" void *g_BombDataAnmMgr = 0;  // void*        @ 0x4b9e44 (BombData.cpp)
// GameManager pointers (string / state slots).
extern "C" void *g_GameMgrG0x1347938 = 0;
extern "C" char *g_GameMgrG0x497e1c = 0;
extern "C" char *g_GameMgrG0x497e30 = 0;
extern "C" char *g_GameMgrG0x497e58 = 0;
extern "C" char *g_GameMgrG0x497e84 = 0;
extern "C" char *g_GameMgrG0x497f4c = 0;
extern "C" char *g_GameMgrG0x498010 = 0;
extern "C" char *g_GameMgrG0x498038 = 0;
extern "C" char *g_GameMgrG0x498064 = 0;
extern "C" char *g_GameMgrG0x498524 = 0;
extern "C" char *g_GameMgrG0x4986b4 = 0;
extern "C" char *g_GameMgrG0x49f560 = 0;
extern "C" char *g_GameMgrG0x49f588 = 0;
extern "C" char *g_GameMgrG0x49f58c = 0;
extern "C" void *g_GameMgrG0x1347f9c = 0;
// Gui object pointer (Player.cpp / Supervisor.cpp).
extern "C" void *g_GuiObjPtr = 0;
// Pbg4 LZSS static state (Pbg4Parser references).
extern "C" i32 g_Pbg4CurIndex = 0;
extern "C" u8 g_Pbg4Dict[0x10000] = {0};   // document-only: orig is u32[0x4000]
extern "C" u8 g_Pbg4Nodes[0x8000] = {0};
// ScreenEffect Rng instance (ScreenEffect.cpp).
extern "C" void *g_ScreenEffectRng = 0;
// Supervisor rdata/state pointers (Supervisor.cpp).
extern "C" void *g_SupervisorG0x496c0c = 0;
extern "C" void *g_SupervisorG0x4980c4 = 0;
extern "C" void *g_SupervisorG0x4bd994 = 0;
extern "C" void *g_SupervisorG0x575a64 = 0;
extern "C" void *g_SupervisorG0x575a68 = 0;
// Player-specific AnmManager / ScoreSub / EffectManager / SoundManager handles.
extern "C" void *g_AnmManagerFilesObj_P = 0;  // document-only alias (not currently referenced)

// AnmManager::ExecuteScript rdata float constants (orig .rdata slots).
// These mirror the const-float DAT_ addresses read absolutely by FUN_00450d60.
extern "C" const f32 g_AnmMgrC0x498a4c = 0.0f;   // DAT_00498A4C (sentinel)
extern "C" const f32 g_AnmMgrC0x498a54 = 1.0f;   // DAT_00498A54 (angle modulus)
extern "C" const f32 g_AnmMgrC0x498b5c = -1.0f;  // DAT_00498B5C (scale flip)
// Supervisor.framerateMultiplier mirror (orig 0x575ac8); ExecuteScript reads
// it absolutely. Zero-init matches the boot state until Supervisor sets it.
extern "C" f32 g_AnmMgrFramerateMul_575ac8 = 0.0f;

